[package]
name = "buoy-sdl2"
version = "0.1.0"
authors = ["Will Cassella <wcassella@gmail.com>"]
edition = "2018"

[dependencies.sdl2]
version = "0.31.0"
features = ["bundled", "static-link"]

[dependencies.buoy]
path = "../buoy"
